name: $(Date:yyyyMMdd).$(Rev:r)
variables:
  DEBIAN_FRONTEND: "noninteractive"
trigger:
  batch: false
  branches:
    include: [ "master" ]
  paths:
    exclude: [ "README.md" ]

jobs:
  - job: image
    displayName: "build image"
    pool:
      vmImage: "ubuntu-16.04"
    workspace:
      clean: all
    timeoutInMinutes: 120

    strategy:
      matrix:
        "1.12.2":
          REVISION: '1.12.2'

    steps:
    - bash: |
        sudo apt-get -y update
        sudo apt-get -y install git openjdk-8-jre-headless wget
      displayName: 'install deps'

    - bash: |
        chmod +x ./build.sh
        ./build.sh
      displayName: 'image build'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        artifactName: '$(REVISION)'
